---
- name: update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: no
  tags:
    - install

- name: install dependencies
  apt:
    name:
      - curl
      - unzip
    state: present
    cache_valid_time: 3600
  tags:
    - install

- name: install consul bash completion
  get_url:
    url: "{{ consul_bash_completion_src }}"
    dest: "{{ consul_bash_completion_dest }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - install

- name: install consul
  unarchive:
    src: "{{ consul_src }}"
    dest: "{{ consul_dest }}"
    mode: 0755
    remote_src: yes
  tags:
    - install

- name: ensure consul run directory
  file:
    path: "{{ consul_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - install

- name: ensure consul run data directory
  file:
    path: "{{ consul_data_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - install

- name: ensure consul config directory
  file:
    path: "{{ consul_conf_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - install

- assert:
    that:
      - 'consul_mode in ("client", "server")'

- name: put consul configuration
  template:
    src: "consul.json.j2"
    dest: /etc/consul.d/config.json
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration

- name: put systemd configuration
  template:
    src: "consul.service.j2"
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == 'xenial'

- name: put upstart configuration
  template:
    src: "consul.upstart.conf.j2"
    dest: /etc/init/consul.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == 'trusty'

- name: enable consul
  service:
    name: consul
    enabled: "{{ consul_service_enabled }}"
  tags:
    - service

- name: start consul
  service:
    name: consul
    state: started
  when: consul_service_started
  tags:
    - service

- name: wait consul
  wait_for:
    host: 127.0.0.1
    port: 8500
    delay: 1
    timeout: 300

- include: dnsmasq.yml
  when: consul_dnsmasq
  tags:
    - dnsmasq
